-- Initial migration - run: npx prisma migrate dev --name init
-- This file is auto-generated by Prisma. Run the command above instead of this file directly.

-- CreateTable: users, problems, notes, sheets, etc.
-- All tables defined in schema.prisma will be created automatically.
-- Run: cd backend && npx prisma migrate dev --name init
